package com.clinichub.adapters.web.reference.controllers;

import com.clinichub.adapters.web.reference.dto.CityDto;
import com.clinichub.adapters.web.reference.dto.CreateCityDto;
import com.clinichub.adapters.web.reference.dto.UpdateCityDto;
import com.clinichub.core.shared.types.CityId;
import com.clinichub.core.shared.types.CountryId;
import com.clinichub.core.reference.domain.City;
import com.clinichub.core.reference.usecase.CreateCity;
import com.clinichub.core.reference.usecase.GetCity;
import com.clinichub.core.reference.usecase.ListCities;
import com.clinichub.core.reference.usecase.UpdateCity;
import com.clinichub.shared.mappers.CityDtoMapper;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

@RestController
@RequestMapping("/api/cities")
@RequiredArgsConstructor
public class CityController {
    
    private final CreateCity createCity;
    private final GetCity getCity;
    private final ListCities listCities;
    private final UpdateCity updateCity;
    private final CityDtoMapper cityDtoMapper;
    
    @PostMapping
    public ResponseEntity<CityDto> createCity(@RequestBody CreateCityDto dto) {
        City city = createCity.execute(new CreateCity.Command(
            new CityId(null), // Will be generated by database
            dto.name(),
            new CountryId(dto.countryId())
        ));
        
        return ResponseEntity.status(HttpStatus.CREATED)
            .body(cityDtoMapper.toDto(city));
    }
    
    @GetMapping("/{id}")
    public ResponseEntity<CityDto> getCity(@PathVariable Long id) {
        Optional<City> city = getCity.execute(new CityId(id));
        return city.map(c -> ResponseEntity.ok(cityDtoMapper.toDto(c)))
            .orElse(ResponseEntity.notFound().build());
    }
    
    @GetMapping
    public ResponseEntity<List<CityDto>> listCities(@RequestParam(required = false) Long countryId) {
        List<City> cities;
        if (countryId != null) {
            cities = listCities.execute(new CountryId(countryId));
        } else {
            cities = listCities.execute();
        }
        
        List<CityDto> cityDtos = cities.stream()
            .map(cityDtoMapper::toDto)
            .toList();
        return ResponseEntity.ok(cityDtos);
    }
    
    @PutMapping("/{id}")
    public ResponseEntity<CityDto> updateCity(@PathVariable Long id, @RequestBody UpdateCityDto dto) {
        Optional<City> city = updateCity.execute(new UpdateCity.Command(
            new CityId(id),
            dto.name(),
            dto.countryId() != null ? new CountryId(dto.countryId()) : null
        ));
        
        return city.map(c -> ResponseEntity.ok(cityDtoMapper.toDto(c)))
            .orElse(ResponseEntity.notFound().build());
    }
}





