package com.clinichub.adapters.web.reference.controllers;

import com.clinichub.adapters.web.reference.dto.CountryDto;
import com.clinichub.adapters.web.reference.dto.CreateCountryDto;
import com.clinichub.adapters.web.reference.dto.UpdateCountryDto;
import com.clinichub.core.shared.types.CountryId;
import com.clinichub.core.reference.domain.Country;
import com.clinichub.core.reference.usecase.CreateCountry;
import com.clinichub.core.reference.usecase.GetCountry;
import com.clinichub.core.reference.usecase.ListCountries;
import com.clinichub.core.reference.usecase.UpdateCountry;
import com.clinichub.shared.mappers.CountryDtoMapper;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

@RestController
@RequestMapping("/api/countries")
@RequiredArgsConstructor
public class CountryController {
    
    private final CreateCountry createCountry;
    private final GetCountry getCountry;
    private final ListCountries listCountries;
    private final UpdateCountry updateCountry;
    private final CountryDtoMapper countryDtoMapper;
    
    @PostMapping
    public ResponseEntity<CountryDto> createCountry(@RequestBody CreateCountryDto dto) {
        Country country = createCountry.execute(new CreateCountry.Command(
            new CountryId(null), // Will be generated by database
            dto.name()
        ));
        
        return ResponseEntity.status(HttpStatus.CREATED)
            .body(countryDtoMapper.toDto(country));
    }
    
    @GetMapping("/{id}")
    public ResponseEntity<CountryDto> getCountry(@PathVariable Long id) {
        Optional<Country> country = getCountry.execute(new CountryId(id));
        return country.map(c -> ResponseEntity.ok(countryDtoMapper.toDto(c)))
            .orElse(ResponseEntity.notFound().build());
    }
    
    @GetMapping
    public ResponseEntity<List<CountryDto>> listCountries() {
        List<Country> countries = listCountries.execute();
        List<CountryDto> countryDtos = countries.stream()
            .map(countryDtoMapper::toDto)
            .toList();
        return ResponseEntity.ok(countryDtos);
    }
    
    @PutMapping("/{id}")
    public ResponseEntity<CountryDto> updateCountry(@PathVariable Long id, @RequestBody UpdateCountryDto dto) {
        Optional<Country> country = updateCountry.execute(new UpdateCountry.Command(
            new CountryId(id),
            dto.name()
        ));
        
        return country.map(c -> ResponseEntity.ok(countryDtoMapper.toDto(c)))
            .orElse(ResponseEntity.notFound().build());
    }
}


